# Jupyter Book configuration
title: dd-coresets Documentation
author: Carlos R. B. Azevedo

# Execute notebooks
execute:
  execute_notebooks: "off"
  timeout: 60

# Parse and execute notebooks
parse:
  myst_enable_extensions:
    - colon_fence
    - ampersand
    - html_image

# Repository settings
repository:
  url: https://github.com/crbazevedo/dd-coresets
  branch: main

# HTML settings
html:
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: true
  use_download_button: true
  home_page_in_navbar: true
  baseurl: ""

# LaTeX
latex:
  latex_engine: pdflatex

# Sphinx settings
sphinx:
  config:
    html_theme_options:
      navigation_depth: 2
      show_prev_next: true
      logo_only: false
